name: test

on:
  push:
    branches:
      gh-16
    paths:
      - '**/*.h'
      - '**/*.PL'
      - '**/*.pm'
      - '**/*.t'
      - '**/*.xs'

env:
  CI: true

jobs:
  skip-duplicate-runs:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@12aca0a884f6137d619d6a8a09fcc3406ced5281
        with:
          concurrent_skipping: 'same_content'
          paths: '["**/*.{h,xs,pm,t,PL}"]'

  test:
    needs: skip-duplicate-runs
    if: ${{ needs.skip-duplicate-runs.outputs.should_skip != 'true' }}
    name: 'Perl v${{ matrix.perl }} on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: ['windows-latest']

        # Strawberry Perl 5.8, 5.10 and 5.12 aren't supported
        # https://github.com/shogo82148/actions-setup-perl/issues/872#issuecomment-939601549
        perl: ['5.14', '5.20', '5.30', '5.32']

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up perl v${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: strawberry
          perl-version: ${{ matrix.perl }}

      - run: perl -V

        # this also upgrades ExtUtils::MakeMaker to the latest version
      - run: cpanm --notest Test::Pod

      - run: cpanm --installdeps --notest .
      - run: perl Makefile.PL

      - name: which make
        run: perl -MConfig -e 'print $Config{make}, $/'

      - name: make
        run: perl -MConfig -e 'exec $Config{make}'

      - name: make test
        run: perl -MConfig -e 'exec $Config{make}, "test"'
